# Generated by Django 4.2 on 2023-05-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0002_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In progress')], max_length=50, null=True),
        ),
    ]
