# Generated by Django 4.2 on 2023-05-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0003_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
